### ISSUE TITLE
在Android Q机子上出现闪退

### ISSUE THREAD

**Issue by Eccentric11** [everhad/AndroidRatingStar#5]
java.lang.IllegalArgumentException: Invalid Layer Save Flag - only ALL_SAVE_FLAGS is allowed
	at android.graphics.Canvas.checkValidSaveFlags(Canvas.java:378)
	at android.graphics.Canvas.saveLayerAlpha(Canvas.java:583)
	at com.idlestar.ratingstar.RatingStarView.drawPartialStar(RatingStarView.java:363)
	at com.idlestar.ratingstar.RatingStarView.onDraw(RatingStarView.java:315)
	at android.view.View.draw(View.java:20234)
	at android.view.View.updateDisplayListIfDirty(View.java:19109)
	at android.view.View.draw(View.java:19962)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
	at android.view.View.updateDisplayListIfDirty(View.java:19100)
	at android.view.View.draw(View.java:19962)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
	at android.view.View.updateDisplayListIfDirty(View.java:19100)
	at android.view.View.draw(View.java:19962)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
	at android.view.View.updateDisplayListIfDirty(View.java:19100)
	at android.view.View.draw(View.java:19962)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
	at android.view.View.draw(View.java:20237)
	at android.view.View.updateDisplayListIfDirty(View.java:19109)
	at android.view.View.draw(View.java:19962)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
	at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4703)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
	at android.view.View.draw(View.java:20237)
	at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:4107)
	at android.view.View.updateDisplayListIfDirty(View.java:19109)
	at android.view.View.draw(View.java:19962)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
	at android.view.View.updateDisplayListIfDirty(View.java:19100)
	at android.view.View.draw(View.java:19962)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
	at android.view.View.updateDisplayListIfDirty(View.java:19100)
	at android.view.View.draw(View.java:19962)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
	at android.view.View.draw(View.java:20237)
	at android.support.v4.widget.NestedScrollView.draw(NestedScrollView.java:1819)
	at android.view.View.updateDisplayListIfDirty(View.java:19109)
	at android.view.View.draw(View.java:19962)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
	at com.scwang.smartrefresh.layout.SmartRefreshLayout.dispatchDraw(SmartRefreshLayout.java:759)
	at android.view.View.updateDisplayListIfDirty(View.java:19100)
	at android.view.View.draw(View.java:19962)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
	at android.view.View.draw(View.java:20237)
	at android.view.View.updateDisplayListIfDirty(View.java:19109)
	at android.view.View.draw(View.java:19962)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
	at android.view.View.updateDisplayListIfDirty(View.java:19100)
	at android.view.View.draw(View.java:19962)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
	at android.view.View.updateDisplayListIfDirty(View.java:19100)
	at android.view.View.draw(View.java:19962)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
	at android.view.View.updateDisplayListIfDirty(View.java:19100)
	at android.view.View.draw(View.java:19962)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
	at android.view.View.updateDisplayListIfDirty(View.java:19100)
	at android.view.View.draw(View.java:19962)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
	at android.view.View.updateDisplayListIfDirty(View.java:19100)
	at android.view.View.draw(View.java:19962)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
	at android.view.View.updateDisplayListIfDirty(View.java:19100)
	at android.view.View.draw(View.java:19962)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
	at android.view.View.draw(View.java:20237)
	at com.android.internal.policy.DecorView.draw(DecorView.java:784)
	at android.view.View.updateDisplayListIfDirty(View.java:19109)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:801)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3391)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3188)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2557)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1527)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7394)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1036)
	at android.view.Choreographer.doCallbacks(Choreographer.java:832)
	at android.view.Choreographer.doFrame(Choreographer.java:767)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by chinowang** [comment]
canvas.saveLayerAlpha(r.left, r.top, r.right, r.bottom, 0xff, CLIP_SAVE_FLAG);
换成 
canvas.saveLayerAlpha(r.left, r.top, r.right, r.bottom, 0xff, Canvas.ALL_SAVE_FLAG);
